# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 140, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.button_reg = QtWidgets.QPushButton(self.centralwidget)
        self.button_reg.setGeometry(QtCore.QRect(140, 190, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.button_reg.setFont(font)
        self.button_reg.setObjectName("button_reg")
        self.reg_login = QtWidgets.QLineEdit(self.centralwidget)
        self.reg_login.setGeometry(QtCore.QRect(230, 90, 113, 20))
        self.reg_login.setObjectName("reg_login")
        self.reg_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.reg_pass.setGeometry(QtCore.QRect(230, 120, 113, 20))
        self.reg_pass.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.reg_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.reg_pass.setObjectName("reg_pass")
        self.reg_pass1 = QtWidgets.QLineEdit(self.centralwidget)
        self.reg_pass1.setGeometry(QtCore.QRect(270, 150, 113, 20))
        self.reg_pass1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.reg_pass1.setObjectName("reg_pass1")
        self.still_reg = QtWidgets.QPushButton(self.centralwidget)
        self.still_reg.setGeometry(QtCore.QRect(280, 190, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.still_reg.setFont(font)
        self.still_reg.setObjectName("still_reg")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 568, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Логин"))
        self.label_2.setText(_translate("MainWindow", "Пароль"))
        self.label_3.setText(_translate("MainWindow", "Повторите пароль"))
        self.button_reg.setText(_translate("MainWindow", "Зарегестрироваться"))
        self.still_reg.setText(_translate("MainWindow", "Я уже зарегестрирован"))
        self.label_4.setText(_translate("MainWindow", "РЕГИСТРАЦИЯ"))
